FORMAT: 1A
HOST: http://factory.zone/api/v1/

# Company API

Provides services for Company features 

## Companies [/company{?page,size}]

### Create Company[POST]

+ Request (application/json)
    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "companyName" : "Gaagle"
                "companyDescription" : "We build everything"
                "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "companyURL" : "gaagle.factory.zone"
            }    
        
            
            
+ Response 201 (application/json)

    + Headers 
        
            Location: /company/:id
    
    + Body
    
            {
                "user_id":2
                "company_id":1
                "companyName" : "Gaagle"
                "companyDescription" : "We build everything"
                "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "companyURL" : "gaagle.factory.zone"
                "createdAt":"2017-6-21 08:12:05"

            }

### List Companies [GET]

+ Parameters
    + page(required, number,`1`)...'page' number
    + size(required, number, `10`)... page 'size'

+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600

    + Body
            
            {
                                    
                "page":
                {
                    "number":1,
                    "size":10 
                    "totalPages": 20
                },
                "companies":
                [
                    {
                        "user_id":2
                        "company_id": 1
                        "companyName" : "Gaagle"
                        "companyDescription" : "We build everything"
                        "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                        "companyURL" : "gaagle.factory.zone"
                        "createdAt":"2017-12-01 13:21:14"
                        "updatedAt": "2017-12-01 21:00:00"
                    },
                    {
                        "user_id":2
                        "company_id": 3
                        "companyName" : "Amzin"
                        "companyDescription" : "We sell everything"
                        "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                        "companyURL" : "amzin.factory.zone"
                        "createdAt":"2017-12-01 13:21:14"
                        "updatedAt": "2017-12-01 21:00:00"
                    }
                ]
            }
            
## Company [/company/{company_id}]
+ Parameters
    + company_id(required, number,`1`)

### View Company [GET]
+ Request

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    
+ Response 200 (application/json)
 
    + Headers
        
            ETag : "euyfewuyfvew76f7"
            cache-control: max-age=600

    + Body
    
            {
                "companyName" : "Gaagle"
                "companyDescription" : "We build everything"
                "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "companyURL" : "gaagle.factory.zone"
                "user_id":2
                "company_id":1
                "createdAt" : "2017-6-21 08:12:05"
                "updatedAt" : "2017-12-01 13:21:14"
            }
            
### Edit Company [PUT]

+ Request (application/json)

    +   Headers 
            
            Authorization: Basic dXNlcjpwYXNzd29yZA==
            x-api-version: 1.0
    + Body
            
            {
                "companyName" : "Gaagle"
                "companyDescription" : "We build life"
                "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "companyURL" : "gaagle.factory.zone"
            }  
+ Response 200 (application/json)

    + Headers
        
            Location: /company:id
    
    + Body
    
            {
                "user_id":1
                "company_id":1
                "companyName" : "Gaagle"
                "companyDescription" : "We build life"
                "companyImagePath" : "http//factory.zone/Projects?id=1/image.png"
                "companyURL" : "gaagle.factory.zone"
                "createdAt" : "2017-6-21 08:12:05"
                "updatedAT": "2018-02-31 03:20:00"
            }

### Delete Company [DELETE]
+ Response 204